# Generated by fusen: do not edit by hand

#' R6 Class for the business logic of the app
#'
#' @description
#' It does the data cleaning and generates text and chart for the app.
#' @export
BusinessLogic <- R6::R6Class(
  "BusinessLogic",
  public = list(
    #' @field months Month numbers and their names.
    months = tibble::tibble(
      month_number = 1:12,
      month_name = month.name
    ),
    #' @field metrics Available metrics.
    metrics = c(
      "Departure delay" = "dep_delay",
      "Arrival delay" = "arr_delay"
    ),
    #' @field data Will store the data..
    data = NULL,
    #' @field unique_carriers Available carriers.
    unique_carriers = NULL,
    #' @field results Where results are stored.
    results = list(
      title = NULL,
      text = NULL,
      chart = NULL
    ),
    #' @description
    #' Create a new business logic object.
    #' @return A new `BusinessLogic` object.
#' @examples
#' business_logic <- BusinessLogic$new()
#' 
#' business_logic$generate_results("9E", 1, "arr_delay", 30)
#' 
#' business_logic$results$title
#' 
#' business_logic$results$text
#' 
#' business_logic$results$chart
    initialize = function() {
      self$data <- nycflights13::flights
      
      self$unique_carriers <- nycflights13::airlines %>%
        dplyr::mutate(name = name %>%
                        stringr::str_remove_all(" Inc.") %>%
                        stringr::str_remove_all(" Corporation"))
    },
    #' @description
    #' Generate results.
    #' @param carrier_filter Carrier for report.
    #' @param month_filter Month for report.
    #' @param metric_filter Metric for report.
    #' @param threshold Threshold for report.
    generate_results = function(
      carrier_filter,
      month_filter,
      metric_filter,
      threshold
    ) {
      filtered_data <- self$data %>%
        dplyr::filter(
          carrier == carrier_filter,
          month == month_filter,
          .data[[metric_filter]] >= 0
        ) %>%
        dplyr::group_by(day) %>%
        dplyr::summarize(metric = mean(.data[[metric_filter]], na.rm = TRUE))
      
      month <- self$months %>%
        dplyr::filter(month_number == month_filter) %>%
        dplyr::pull(month_name)
      
      carrier <- self$unique_carriers %>%
        dplyr::filter(carrier == carrier_filter) %>%
        dplyr::pull(name)
      
      
      number_of_days <- filtered_data %>%
        dplyr::filter(metric > threshold) %>%
        nrow()
      
      metric <- dplyr::if_else(
        metric_filter == "dep_delay",
        "departures",
        "arrivals"
      )
      
      self$results$title <- "{month}: {carrier}" %>%
        glue::glue()
      
      self$results$text <- "In {month} {carrier} had {number_of_days} days with {metric} delayed by more than {threshold} minutes." %>%
        glue::glue()
      
      self$results$chart <- filtered_data %>%
        dplyr::mutate(day = factor(day)) %>%
        ggplot2::ggplot(ggplot2::aes(day, metric)) +
        ggplot2::geom_line(group = 1) +
        ggplot2::geom_hline(
          yintercept = threshold,
          lty = "dashed",
          color = "red"
        ) +
        ggplot2::labs(
          title = "Average {metric} delay per day for {carrier} in {month}" %>%
            glue::glue(),
          x = "Day of the month",
          y = "Average delay [minutes]"
        )
    }
  )
)
